#+SETUPFILE: ~/.emacs.d/SETUPFILE.org
#+TITLE: Stowers Computing Environment (sce) \n Linux package management with guix
#+DATE: <2015-06-08 Mon>
#+AUTHOR: Malcolm Cook
#+EMAIL: malcolm.cook@gmail.com

* Administering guix
Installing, Configuring & Deploying guix
** Deploying Base Machine (Mango/Catalpa)

 + Building on minimally configued CentOS7 (TBW: jenny? define
   minimal - ie.. missing help2man inter alia)

** packages installed by Jenny/Dustin on mango at my request
these packages are on top of the original base install image
#+BEGIN_SRC sh
sudo yum install libtk (needed by R library MASS and expected to be found on local host).
#+END_SRC


** Install build preconditions on GUIX_SRVR 


In particular, package abrt-console-notification needs to be current
(which fixes recent recognized upstream bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1139001 with a
corresponding fix: https://rhn.redhat.com/errata/RHBA-2015-0556.html)

This will be included by a current
#+BEGIN_SRC sh
yum -y update
#+END_SRC

#+CAPTION: Install required vendor packages
#+BEGIN_SRC sh
sudo yum -y groupinstall "X Window System" "Desktop" "Fonts" "General Purpose Desktop"
sudo yum -y install autoconf 
sudo yum -y install automake
sudo yum -y install bzip2
sudo yum -y install gettext 
sudo yum -y install gettext-devel # nb gettext on centOS which is at latest already!g
sudo yum -y install gnupg
sudo yum -y install gnutls
sudo yum -y install graphviz
sudo yum -y install guile
sudo yum -y install guile-devel ## includes guile.m4, a dependency of guix ./bootstrap
sudo yum -y install help2man
sudo yum -y install libgcrypt-devel
sudo yum -y install make
sudo yum -y install pkgconfig 
sudo yum -y install sqlite
sudo yum -y install sqlite-devel
sudo yum -y install texinfo
sudo yum -y install texinfo-tex
#+END_SRC

TODO: could not get gnutls guile to work

in order for guile to pick up JSON, just
GUILE_LOAD_PATH="/usr/local/share/guile/site:$GUILE_LOAD_PATH" guile
TODO?: re-install guile-json elsehow?

#+CAPTION: install gnutls
#+BEGIN_SRC sh
wget ftp://ftp.gnutls.org/gcrypt/gnutls/v3.3/gnutls-3.3.16.tar.xz
tar xf gnutls-3.3.16.tar.xz
cd gnutls-3.3.16
  --with-libdir=lib64 \
./configure \
  --with-guile-site-dir=no \  ## This will instruct GnuTLS to
				      ## attempt to install the Guile
				      ## bindings where Guile will
				      ## look for them. It will use
				      ## guile-config info pkgdatadir
				      ## to learn the path to use make
# sudo ldconfig suggested by https://lists.gnupg.org/pipermail/gnutls-help/2013-May/003145.html without which
# make errors with:
#../lib/.libs/libgnutls.so: undefined reference to `nettle_secp_224r1'
#../lib/.libs/libgnutls.so: undefined reference to `nettle_secp_192r1'

make
make test
make install

#+END_SRC

#+CAPTION: install guile
#+BEGIN_SRC sh
git clone git://git.savannah.nongnu.org/guile-json.git
cd guile-json
autoreconf -i			#  kudos http://askubuntu.com/questions/27677/cannot-find-install-sh-install-sh-or-shtool-in-ac-aux
./configure
make
sudo make install
#+END_SRC



** Configure NFS share

#+CAPTION: create NSF exported ${GNU}   - TODO TBW by jenny?
#+BEGIN_SRC sh


#+END_SRC


#+CAPTION: configure SHELL environment for guix 

#+BEGIN_SRC sh
cat <<'EOF' > guix.init.sh
GUIX_SRVR=catalpa.sgc.loc
GNU=/gnu
export PATH=${GNU}/bin:"${PATH}"
export MANPATH=${GNU}/bin:"${PATH}"
GUIX_PROFILE="$HOME/.guix-profile" \
source "$HOME/.guix-profile/etc/profile"
#export PATH="${HOME}/.guix-profile/bin:${PATH}"
#export MANPATH="${HOME}/.guix-profile/man"
EOF
#+END_SRC


NOTEs: 

 - /gnu must be mounted without root squashing
 - `make check` fails in NFS mount home since default file perms
   include NFS_FACL of 'x' (which is arguable wrong).  So, build and
   test/check is happening (for now) in /tmp (which has advantage
   anyway of being faster)
 - deploy to /gnu mounted as network share
 - appropriate configure and/or make options

#+CAPTION: install guix, following http://www.gnu.org/software/guix/download/
#+BEGIN_SRC sh

#ssh mango
ssh catalpa
bld=/tmp/mec/sce
mkdir -p ${bld}
cd ${bld}

################################################################################
# binary (re)installation - following http://www.gnu.org/software/guix/manual/html_node/Binary-Installation.html with changes for shared /gnu
systemctl stop guix-daemon.service # allows to close any files which might be open in the store so they can be deleted
VAR=/var
NIX_STATE_DIR=${VAR}/guix
cd /tmp
rm -rf ./var ./gnu
wget ftp://alpha.gnu.org/gnu/guix/guix-binary-0.8.3.x86_64-linux.tar.xz
tar xf guix-binary-0.8.3.x86_64-linux.tar.xz --warning=no-timestamp
rm -rf /var/guix /gnu/var/guix 
rm -rf /gnu/* 
mv gnu/* /gnu # which currently moves only /gnu/store
mv var/guix ${VAR} # instead of localhost
##adjust symlinks
ln -sf -T ${VAR}/guix/profiles/per-user/root/guix-profile-1-link ${VAR}/guix/profiles/per-user/root/guix-profile 
ln -sf -T ${VAR}/guix/profiles ${VAR}/guix/gcroots/profiles
ln -sf ${VAR}/guix/profiles/per-user/root/guix-profile ~root/.guix-profile
# change the name of the group
perl -pi -e 's/guixbuild/guix-builder/g'  ~root/.guix-profile/lib/systemd/system/guix-daemon.service 
# install it as a service
/bin/cp -f ~root/.guix-profile/lib/systemd/system/guix-daemon.service /etc/systemd/system
# start the daemon as a service
systemctl start guix-daemon.service
# alternatively, run the daemon from the command line
#~root/.guix-profile/bin/guix-daemon --build-users-group=guix-builder
# make command available to all users:
mkdir /gnu/bin
export PATH=/gnu/bin:"${PATH}"
ln -s -f -t /gnu/bin  ${VAR}/guix/profiles/per-user/root/guix-profile/bin/guix
guix archive --authorize < ~root/.guix-profile/share/guix/hydra.gnu.org.pub
################################################################################
## first packages
guix package -i glibc-utf8-locales ## glibc-locales
export LOCPATH=$HOME/.guix-profile/lib/locale
guix package -i fontconfig
guix package -i gs-fonts
guix package -i font-dejavu
guix package -i font-gnu-freefont
guix package -i emacs
guix package -i gdk-pixbuf # needed by emacs 
export PATH="/root/.guix-profile/bin:/root/.guix-profile/sbin:${PATH}"
gdk-pixbuf-query-loaders  --update-cache
guix package -i libcanberra # needed by emacs - along with:
export GTK_PATH=/gnu/store/*-libcanberra-0.30/lib/gtk-3.0/modules

if [ -z "$GTK_MODULES" ] ; then     
        GTK_MODULES="libcanberra-gtk-module"
else
        GTK_MODULES="$GTK_MODULES:libcanberra-gtk-module"
fi

guix package -i gnome-icon-theme

################################################################################
guix build samtools

################################################################################

wget ftp://alpha.gnu.org/gnu/guix/guix-0.8.3.tar.gz.sig
tar xf guix-0.8.3.tar.gz
cd guix-0.8.3
################################################################################
# first time git clone git://git.savannah.gnu.org/guix.git 
cd guix
git pull

################################################################################

make clean
./bootstrap
#./configure --localstatedir=/gnu/var --exec-prefix=/gnu  
./configure --prefix=/gnu   ## --localstatedir=/gnu/var --exec-prefix=/gnu  
j=40
make -j $J
#make doc/guix.info # allowing: info -f doc/guix.info
make doc/guix.pdf # requires texi2dvi
make doc/guix.html
make -j $j check    

# mv guix-0.8.3 ~/project/sce/ # from tmp into project
# rm -rf  guix-0.8.3* & # clean up tmp
# chmod -R u=rwx  guix-0.8.3 # some didn't want to delete
# rm -rf  guix-0.8.3* & # clean up tmp

## some temp dirs 
##su - guix # become user guix
##cd ~mec/project/sce/guix-0.8.3

ssh catalpa
sudo su 
bld=/tmp/mec/sce
mkdir -p ${bld}
cd ${bld}
rm -rf guix
scp -q -r mec@mango:/tmp/mec/sce/guix .
cd guix
make install  # any value to separately install-data install-exec 

export PATH=/gnu/bin:"${PATH}"

guix archive --authorize < ~root/.guix-profile/share/guix/hydra.gnu.org.pub

systemctl start guix-daemon.service


# start the daemon

#killall guix-daemon # in case already running (i.e. we're developing this install/configure recipe)
#nohup /gnu/bin/guix-daemon --build-users-group=guix-builder &
tail -f /root/nohup.out &
##&2> /var/log/guix-daen.log & ## TODO: get into system.d - have it log - with rotation
systemctl restart guix-daemon.service
systemctl status guix-daemon.service

#rm -rf /gnu/var/guix/profiles/per-user ## the doc says this should happen by the daemon but not!  FIXME! BUG?
mkdir /gnu/var/guix/profiles/per-user ## the doc says this should happen by the daemon but not!  FIXME! BUG?
chmod a+w /gnu/var/guix/profiles/per-user

exit # return to be mec on catalpa
export PATH=/gnu/bin:"${PATH}"
guix build hello
guix package -i hello
# 

guix package -i socat

sudo su
guix package -i socat

## on GUIX_SRVR


/root/.guix-profile/bin/socat TCP4-LISTEN:9999  UNIX:/var/guix/daemon-socket/socket

## On a client node where /gnu is mounted read-write I ran this:

export GUIX_DAEMON_SOCKET=/gnu/var/guix/daemon-socket/`hostname`-socat  & socat UNIX-LISTEN:${GUIX_DAEMON_SOCKET}  TCP4:guix-builder:9999

##socat UNIX-LISTEN:/home/rwurmus/foo TCP4:guix-builder:9999 &    export GUIX_DAEMON_SOCKET=$HOME/foo

At this point I could use

    guix build hello
    guix environment hello


#+END_SRC

TODO: ensure to use the branch corresponding to release

Considerations:
 ./configure options:
 - localstatedir " is the value passed to configure as
   --localstatedir" per convention defined in [[https://www.gnu.org/prep/standards/html_node/Directory-Variables.html][GNU Coding Standards:
   Directory Variables]]
 -  [[https://gnunet.org/bot/log/guix/2015-02-10][discussion archive]] - 
  - it should be shared -  is /gnu/var

This recipe has me 
 - build/test on mango (which is fast)
 - as mec
 - in /tmp (which is local and therefore does not have wonkey execute
   permission which causes `make check` to fail
 - copy to /tmp on catalpa (where I have root)
 - install from catalpa as root

##localstatedir
NIX_STATE_DIR=/gnu/var

> Alternately, you can also do:
>
>   guix build guix --with-source=/path/to/guix

> One can run:
>
>   GUIX_PROFILE=$HOME/.guix-profile . ~/.guix-profile/etc/profile

TODO: there is also a `guix pull` command - what is that about

** Configuration of quix

Difference from http://www.gnu.org/software/guix/manual/guix.html :
 - /gnu/store is nfs mounted read/write everywhere
 - /gnu is owned by new user, guix (instead of root)
 - guix-daemon runs as guix (not root)

GUIX_DAEMON_SOCKET: "Actually, clients honor the (undocumented) ‘GUIX_DAEMON_SOCKET’
environment variables, so that’s one thing you could use."

#+CAPTION: example of running a single test which proving the install
#+BEGIN_SRC sh
make check TESTS=tests/syscalls.scm 
#+END_SRC


#+CAPTION: Make the "builder users" and their group... 
#+BEGIN_SRC sh
sudo groupadd guix-builder # already exists

for i in `seq 1 10`; do
    sudo useradd -g guix-builder  -G guix-builder           \
                 -d /var/empty -s `which nologin`          \
                 -c "Guix build user $i" \
                 guix-builder$i;
  done

## NOT: in the above --system          \

# Make the /gnu/store directory, where packages are kept/built
#sudo -u guix mkdir -p /gnu/store

sudo -u guix chgrp -R guix-builder /gnu/store
sudo -u guix chmod -R 1775 /gnu/store

## TODO: do we really want/need to permissions to be 3775 - u=rwx,g=rwx,a=rx sticky and set gid
## chgrp -R guix-builder 

ls guix/tests/*.log | xargs -i echo "{}\n" && cat {} >> guix/test.logs

#+END_SRC
Notes:
 - purpose of builder user accounts is to allow the daemon process to offload
   package building while keeping things nicely contained

#+CAPTION: produce confirmatory report on the "builder user"
#+BEGIN_SRC sh
getent passwd guix
getent group guix-builder
getent passwd guix-builder1
#+END_SRC

#+RESULTS:
: guix:$1$E5Ru3NpE$wZZY.cM8TwbRMHBI1UP110:3036:20302:Guix build user:/var/empty:/bin/bash
: guix-builder:!:20302:guix-builder1,guix-builder2,guix-builder3,guix-builder4,guix-builder5,guix-builder6,guix-builder7,guix-builder8,guix-builder9,guix-builder10
: guix-builder1:!!:3048:20302:Guix build user 1:/var/empty:/sbin/nologin

#+CAPTION: Create startup script to deploy within /etc/profile.d
#+BEGIN_SRC sh
sudo cat <<EOF > sce_guix.sh
???
EOF
#+END_SRC

** Deploy: quix
While still 'experimenting', you might not yet want to take this next
'install' step:

Declare alternate location for storing (custom) packages: 
#+BEGIN_SRC sh
gp=$(readline -m ./guix_package)
mkdir gp 
export GUIX_PACKAGE_PATH=${gp}:${GUIX_PACKAGE_PATH}
#+END_SRC
** Advanced guix
*** Creating a new recipe for installing a new application
TBW
*** Using Emacs interface to guix 

install guix.el following https://github.com/alezost/guix.el

** Alternate installation notes 
*** bootstrapping
If guix is already installed, you could
#+BEGIN_SRC sh
guix package --install autoconf automake bzip2 gcc-toolchain gettext \
                             guile libgcrypt pkg-config sqlite

#+END_SRC
** configure emacs
#+BEGIN_SRC lisp
(package-install 'geiser)
(require 'geiser)
(setq-default geiser-guile-load-path '("~/src/guix"))
#+END_SRC
*** Publishing a list of installed packages to our confluence based software catalog
PLAN:
#+BEGIN_QUOTE
How to coordinate guix/plack content with wiki user content:

Have one wiki/confluence page for each scientific applications,
systematiclly named after the app, created according to a template.

Have special section of the page reserved for being written to by guix

have tool to update/create wiki page for any guix managed app

First time we run it it pre-creates all pages for guix managed apps.
#+END_QUOTE

*** Notifying interested parties when packages are updated
Users 'self-select' by watching associated confluence page
** Site configuration
Everyone needs following additional shell
* Using guix

The section presents how to use guix to learn about available
applications, and to get them loaded into your unix environment.

** Using the `guix package` command

You will most often use the `quix package` command to 

*** Learning what applications have already been installed.
TBW
*** Getting details about an installed application.
TBW
*** Learning which installed applications are in your current environment.
TBW
*** Controlling which installed applications are in your current environment.
TBW
*** Setting up a project specific environment.
TBW
*** Learning what applications are available for installation
TBW
*** Using guix instead of python's pip
TBW
*** Enabling reproducible research

* Why guix
TWB
** guix is better than bio.brew
SIMR has gone through a variety of approaches to managing deployment
and documentation of a wide scientific applications over the years.
Most recently, we are using in-house developed bio-brew.

The following issues with current bio.brew approach should be
addressed in this effort.
   + obscure/opaque:
     + it wraps/hides the actual commands that are used to
       configure/make/test/install.  It does this in an attempts to be
       a useful abstraction, but in fact it is not.  The recipes should
       either be in SHELL such as bash, or well documented interface to
       unix system.
     + it only exposes selected parameters to install (i.e. can not
       cause make to run verbosely without changing the wrappers)
     + it adds one more layer between source code and install with
       intervening *undocumented* variables for communicating state
       between recipes and the engine.
   + redundant
     + recipes must explicitly list the files to be installed:
       /n/local/bin/bio.brew/recipes/blast+ which requires recipes to
       be re-written when upstream application changes to change
       binaries.  Most install mantras have their own list.  It should
       be sufficient to simply provide a PREFIX.
   + INCOMPLETE: does not
     + run tests
     + detect collisions (due to either multiple versions of a package,
       or multiple packages with identically named files)
     + install manpages, libraries, (anything other than binaries)
       without special code.
     + provide for environment configuration with shells other than
       bash (i.e. csh is bash only (i.e. for_env assumes bash)
     + allow swapping between alternate builds (i.e. deactivate not supported) 
     + does not handle versioned man pages - or manpages at all for that
       matter
     + environment variables are NOT version specific - not possible to
       have different environments for each versioned install of an app.
     + allow end-user control of apps in end-user environment - it is an all or none affair.
   + ISSUES:
     + advises to 'bb remove full.pkg.name'
     + the 'logs' directory contains non-logs
     + logs are not version specific - installing/building a new version
       overwrites the log of any previous install
     + uses wierd terminology - 'install' does not install typically it
       only builds.
     + installs things using symlinks.  This is unexpected by some apps,
       esp naively coded ones, such as university coded ones like rsem, 
       and leads to long testing/debugging session.
   + TODO: contribute patch of  rsem-calculate-expression to use FindBin::RealBin
* GUIX deployment STATUS / notes to self
- install from source or from 0.8.3 tarball
- how to bootstrap network ready install?
- if build, then
	./configure --prefix=/gnu
or
	./configure --localstatedir=/gnu/var --exec-prefix=/gnu  
- init.d system.d 
- still needed?
 	mkdir /gnu/var/guix/profiles/per-user ## the doc says this should happen by the daemon but not!  FIXME! BUG?
 	chmod a+rwx /gnu/var/guix/profiles/per-user
- TBW: transition plan?
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20381
- "Interacting with a remote daemon" - socat test and report "If you
  could test this and provide feedback about the other options
  discussed there, that would be great (please email
  20381@debbugs.gnu.org.)"

We use 'guix' package manager to manage our CentOS-based
bioinformatics and other scientific computing applications.  This
document describes how to this is done.  The section "Everybody's
guix" shows you the basic package management method you need to see
what applications are installed and how to choose between them.
"Installing, Configuring, and Deploying guix" details the specifics of
our site deployment.  "Q/A" provides answers to questions that were
not readily apparent from a first read of the documentation.  "TODO:"
lists local configurations and integrations that, once performed, will
make guix even more useful to the administrator and
end-user. "References & Links" provides pointers found valuable during
the initial study and deployment of guix.
* Q/A
+ How is package recipe used for alternate versions of the package???
+ How does this approach track with changes in the recipe??
+ How are build options handled (i.e. `make --with-gtk `)???
* TODO:
+ address all TODO/FIXME/TBW items.
+ provide answers to all the Q/A
+ enable/use emacs interface to guix package management
+ socat
+ reports of locally installed packages are posted on wiki
+ feed to install activity
+ method for categorizing packages using tags
+ Document: "Linux package management with guix"
  + is available
    + in github
    + published to wiki
  + is used as base material for series of workshops
* References & Links
+ [[http://www.gnu.org/software/guix/manual/guix.html][GNU Guix Reference Manual]] ([[https://www.gnu.org/software/guix/manual/guix.pdf][pdf]])
+ [[http://arxiv.org/abs/1506.02822][Reproducible and User-Controlled Software Environments in HPC with Guix]]
+ [[http://savannah.gnu.org/git/?group=guix][GNU Guix - Git Repositories on Savannah]]
+ [[https://www.gnu.org/software/guix/package-list.html][GNU Guix Package List]] - lists packages that are part of base guix
  (you get 'out of the box') - includes a few bioinfo packages -
  samtools, bwa, etc
+ [[https://www.gnu.org/software/guix/][GNU's advanced distro and transactional package manager — GuixSD]] - a
  GNU linux distro which uses guix as its package manager.

+ [[http://guix.mdc-berlin.de][A searchable package list]] - 'You can search for “bioinfo” and all
  packages in the bioinformatics module should be displayed.  There
  are also some machine learning packages and statistics packages that
  are used in bioinformatics, but are not located in this module.'
+ dedicated build system for R packages and an importer for CRAN
  packages.  Creating a Guix package expression from a CRAN package
  (e.g. DBI) now takes little more than this:

    guix import cran DBI

  The output is an expression that takes very little editing can be
  bound to a variable in statistics.scm.  To add the package to Guix
  upstream then only requires submitting a simple patch to
  guix-devel@gnu.org.
+ [[http://hackersome.com/p/alezost/guix.el][Emacs interface for Guix package manager]] - out of date - screen shots 
+ [[http://elephly.net/posts/2015-04-17-gnu-guix.html][rekado - GNU Guix in an HPC environment]] -  blog post -
  + refers to set of recipes [[http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/bioinformatics.scm][guix.git - guix bioinformatics source
    archive]]
  + [[https://github.com/BIMSBbioinfo/guix-nonfree/blob/master/bimsb/packages/bioinformatics-nonfree.scm][guix-nonfree/bioinformatics-nonfree.scm]] - Ricardo Wurmus' repos
    of 'non-free' bioinfo apps including: DiNup, macs-1, tophat(!), viennarna
+ [[https://gnunet.org/gnu-guix-initd-script][GNU Guix initd scriptPrimary]] - HowTo: start guix daemon on system startup
+ [[http://dustycloud.org/blog/guix-package-manager-without-make-install/][Guix package manager without "make install"]] - HowTo: run guix out of
  the src tree without installing it
+ [[http://dthompson.us/reproducible-development-environments-with-gnu-guix.html][Reproducible Development Environments with GNU Guix]] - blog post -
  + considers new(ish) `guix environment` command as replacement for
    Python's pip/virtualenv, PHP's composer, node.js' npm
  + demos a package which does not have any source code of its own -
    it only has run-time preconditions of other packages which must be
    "on path". (this is what spack called a "meta-package")
  + demos usage of `--pure` option 
+ https://github.com/pjotrp/guix-notes includes sections on:
  + on installation 
  + [[https://github.com/pjotrp/guix-notes][Hacking Guix]]:
  + current notes / bioinformatics / hacking tips /
  + lots on ruby gems
+ [[https://github.com/BIMSBbioinfo/guix/blob/master/gnu/packages/bioinformatics.scm][(define-module (gnu packages bioinformatics)]  - bioinfo repos - now taken down - 
  including: bedops, bedtools, python2-pybedtools, bowtie,, bwa,
  python2-bx-python, clipper, clustal-omega,
  crossmap,cutadapt,flexbar, hisat, htseq, htsjdk, macs,
  miso,.... samtools, seqan, star, shogun, vcftools,

* Notes/Suggestions/Best Practices:

#+BEGIN_QUOTE
snippets - things poelple do

./pre-inst-env guix build ipcalc --keep-failed ;;; note: source file 

$ ./configure --with-libgcrypt-prefix=$HOME/.guix-profile/
--localstatedir=/var


--prefix=/tmp


#+END_QUOTE

nderstand: binary deployment (when not altering: –with-store-dir OR –localstatedir)

- CURRENTLY: Guix is not designed to be run in a centralised manner. A
  Guix daemon is supposed to run on each system as root and it listens
  to RPCs from local users only. In an environment with multiple
  clusters and multiple workstations this approach requires
  considerable effort to qmake it work correctly and securely.

[[http://www.gnu.org/software/guix/manual/guix.html#Invoking-guix-publish][guix publish]]  - consider using

guix export & import - can translate nix pkgs and be used to move
packages across machines/installations.

#+BEGIN_QUOTE
#+END_QUOTE
* 

#+BEGIN_SRC sh
git config --global user.name "Cook, Malcolm"
git config --global user.email "MEC@stowers.org"

#cd existing-project
git init
git add SCE.org # --all
git add SCE.md # --all
git commit -m "Initial Commit"
git remote add origin http://MEC@stash/scm/cbio/sce.git
git push origin master
#+END_SRC
